spring.application.name=demo30
# DATASOURCE CONFIGURATION
spring.datasource.url=jdbc:mysql://localhost:3306/demo30?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=fakepassword

# JPA / HIBERNATE PROPERTIES
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# LOGGING
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.results=TRACE